In [10]:
import numpy as np
import pandas as pd

In [11]:
movie= pd.read_csv('tmdb_5000_movies.csv')
credit= pd.read_csv('tmdb_5000_credits.csv')

In [8]:
ls

'movie_recomender (1).ipynb'   notebook079ae63ded.ipynb   tmdb_5000_movies.csv
 movie_recomender.ipynb        tmdb_5000_credits.csv      Untitled0.ipynb

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [12]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [ ]:
credit.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [14]:
mvi= movie.merge(credit,on='title')
mvi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [ ]:
mvi.shape

(4809, 23)

In [ ]:
#GENRES
#ID
#KEYWORDS
#OVERVIEW
#TITLE
#CAST
#CREW

In [ ]:
mvi= mvi[['title','id','genres','keywords','overview','cast','crew']]

In [ ]:
mvi.head(1)

,title,id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
mvi.shape

(4809, 7)

In [ ]:
mvi.isnull().sum()

title       0
id          0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [ ]:
mvi.dropna(inplace=True)

In [ ]:
mvi.shape

(4806, 7)

In [ ]:
mvi.duplicated().sum()

0

In [ ]:
mvi.head()

,title,id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
mvi.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
import ast
def convert(obj):
    lis= []
    for i in ast.literal_eval(obj):
        lis.append(i['name'])
    return lis

In [ ]:
mvi['genres'] = mvi.genres.apply(convert)
mvi.keywords = mvi['keywords'].apply(convert)

In [ ]:
mvi.head(1)

,title,id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
mvi.keywords[0]

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [ ]:
mvi.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [ ]:
def convert2(obj):
    lis= []
    temp= 0
    for i in ast.literal_eval(obj):
        if temp == 3:
            break
        lis.append(i['name'])
        temp += 1
    return lis

In [ ]:
mvi.cast = mvi['cast'].apply(convert2)

In [ ]:
mvi.head()

,title,id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
def convert3(obj):
    lis= []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            lis.append(i['name'])
    return lis

In [ ]:
mvi.head(1)

,title,id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
mvi['crew'] = mvi['crew'].apply(convert3)

In [ ]:
mvi.iloc[0].crew

['James Cameron']

In [ ]:
mvi.head()

,title,id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [ ]:
mvi.head(1)

,title,id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [ ]:
def coll(obj):
    lis= []
    for i in obj:
        lis.append(i.replace(" ",""))
    return lis

In [ ]:
mvi['keywords']= mvi['keywords'].apply(coll)
mvi['cast']= mvi['cast'].apply(coll)
mvi['crew']= mvi['crew'].apply(coll)

In [ ]:
mvi['genres']= mvi['genres'].apply(coll)

In [ ]:
mvi.head(1)

,title,id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","In the 22nd century, a paraplegic Marine is di...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]

In [ ]:
mvi.overview= mvi.overview.apply(lambda x: x.split())

In [ ]:
#mvi['tag'] = mvi['overview']+mvi['title']+mvi['overview']+mvi[]
mvi['tags'] = mvi['overview'] + mvi['genres'] + mvi['keywords'] + mvi['cast'] + mvi['crew']

In [ ]:
mvi.head(1)

,title,id,genres,keywords,overview,cast,crew,tags
0,Avatar,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [ ]:
new_df = mvi.drop(columns=['overview','genres','keywords','cast','crew'])

In [ ]:
new_df.head()

,title,id,tags
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,206647,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney..."
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
new_df.shape

(4806, 3)

In [ ]:
new_df['tags']=new_df['tags'].apply(lambda x: " ".join(x))

In [ ]:
new_df.iloc[1].tags

"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. Adventure Fantasy Action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger JohnnyDepp OrlandoBloom KeiraKnightley GoreVerbinski"

In [ ]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [ ]:
lis= []
for g,i in enumerate(new_df['tags']):
    tag = i.split()
    for j,k in enumerate(tag):
        tag[j]= ps.stem(k)
    string = " ".join(tag)
    lis.append(string)

In [ ]:
new_df['tags'] = lis

In [ ]:
new_df['tags'][1]

"captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems. adventur fantasi action ocean drugabus exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditssting johnnydepp orlandobloom keiraknightley goreverbinski"

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
cv.get_feature_names()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity= cosine_similarity(vectors)

In [ ]:
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [ ]:
sorted(list(enumerate(similarity[56])),reverse=True)

[(4805, 0.03251280443811775),
 (4804, 0.030457245193658628),
 (4803, 0.0),
 (4802, 0.0),
 (4801, 0.02530226996846287),
 (4800, 0.0),
 (4799, 0.03458572319330373),
 (4798, 0.027756369082668448),
 (4797, 0.0),
 (4796, 0.0),
 (4795, 0.030772872744833184),
 (4794, 0.0),
 (4793, 0.0),
 (4792, 0.0),
 (4791, 0.0),
 (4790, 0.03829197905337418),
 (4789, 0.0799502686333539),
 (4788, 0.0),
 (4787, 0.0),
 (4786, 0.04891159880445184),
 (4785, 0.025854384499750954),
 (4784, 0.0),
 (4783, 0.04652421051992354),
 (4782, 0.0),
 (4781, 0.03892494720807614),
 (4780, 0.0),
 (4779, 0.0),
 (4778, 0.0),
 (4777, 0.0),
 (4776, 0.0),
 (4775, 0.11134044285378084),
 (4774, 0.04652421051992354),
 (4773, 0.07784989441615228),
 (4772, 0.03143473067309657),
 (4771, 0.0),
 (4770, 0.0),
 (4769, 0.0),
 (4768, 0.0),
 (4767, 0.04767312946227961),
 (4766, 0.0),
 (4765, 0.0),
 (4764, 0.0),
 (4763, 0.05698028822981897),
 (4762, 0.022727272727272724),
 (4761, 0.07207499701564471),
 (4760, 0.0),
 (4759, 0.0),
 (4758, 0.053300179088902604),
 (4757, 0.0),
 (4756, 0.0),
 (4755, 0.03458572319330373),
 (4754, 0.0),
 (4753, 0.0),
 (4752, 0.03892494720807614),
 (4751, 0.055512738165336896),
 (4750, 0.053300179088902604),
 (4749, 0.0),
 (4748, 0.02604661305353116),
 (4747, 0.0),
 (4746, 0.0),
 (4745, 0.0),
 (4744, 0.04029114820126901),
 (4743, 0.01922366120271981),
 (4742, 0.0),
 (4741, 0.04181210050035454),
 (4740, 0.0),
 (4739, 0.0),
 (4738, 0.0),
 (4737, 0.11009637651263604),
 (4736, 0.05698028822981897),
 (4735, 0.025854384499750954),
 (4734, 0.0),
 (4733, 0.04545454545454545),
 (4732, 0.0),
 (4731, 0.03656362120635653),
 (4730, 0.030151134457776358),
 (4729, 0.027076518053694116),
 (4728, 0.025666350116967267),
 (4727, 0.03504998186163908),
 (4726, 0.0),
 (4725, 0.0),
 (4724, 0.0),
 (4723, 0.0),
 (4722, 0.0),
 (4721, 0.07009996372327816),
 (4720, 0.037113480951260276),
 (4719, 0.0),
 (4718, 0.10660035817780521),
 (4717, 0.04351941398892446),
 (4716, 0.0),
 (4715, 0.0),
 (4714, 0.0),
 (4713, 0.0),
 (4712, 0.0),
 (4711, 0.04956815970966097),
 (4710, 0.0),
 (4709, 0.0),
 (4708, 0.0),
 (4707, 0.0),
 (4706, 0.0),
 (4705, 0.0),
 (4704, 0.04181210050035454),
 (4703, 0.044455422447438706),
 (4702, 0.03829197905337418),
 (4701, 0.0),
 (4700, 0.0),
 (4699, 0.03656362120635653),
 (4698, 0.0),
 (4697, 0.0),
 (4696, 0.01914598952668709),
 (4695, 0.026444294267397254),
 (4694, 0.058025885318565944),
 (4693, 0.039590379123244784),
 (4692, 0.0),
 (4691, 0.06917144638660747),
 (4690, 0.0),
 (4689, 0.0),
 (4688, 0.04767312946227961),
 (4687, 0.04652421051992354),
 (4686, 0.03829197905337418),
 (4685, 0.03829197905337418),
 (4684, 0.04891159880445184),
 (4683, 0.0),
 (4682, 0.0),
 (4681, 0.0),
 (4680, 0.0),
 (4679, 0.0),
 (4678, 0.020806259464411975),
 (4677, 0.0337099931231621),
 (4676, 0.037113480951260276),
 (4675, 0.03553345272593507),
 (4674, 0.02956561979945413),
 (4673, 0.11677484162422842),
 (4672, 0.12060453783110543),
 (4671, 0.0),
 (4670, 0.07242068243779012),
 (4669, 0.03768891807222045),
 (4668, 0.04351941398892446),
 (4667, 0.036037498507822355),
 (4666, 0.0),
 (4665, 0.0),
 (4664, 0.0),
 (4663, 0.0),
 (4662, 0.054595109043261404),
 (4661, 0.08362420100070908),
 (4660, 0.0),
 (4659, 0.0),
 (4658, 0.0),
 (4657, 0.03553345272593507),
 (4656, 0.05096471914376255),
 (4655, 0.0),
 (4654, 0.053300179088902604),
 (4653, 0.06917144638660747),
 (4652, 0.0),
 (4651, 0.0),
 (4650, 0.0),
 (4649, 0.0),
 (4648, 0.024618298195866542),
 (4647, 0.027756369082668448),
 (4646, 0.0),
 (4645, 0.04767312946227961),
 (4644, 0.0),
 (4643, 0.0),
 (4642, 0.1305582419667734),
 (4641, 0.10660035817780521),
 (4640, 0.0),
 (4639, 0.0),
 (4638, 0.09304842103984708),
 (4637, 0.0),
 (4636, 0.0753778361444409),
 (4635, 0.0),
 (4634, 0.03413943709994594),
 (4633, 0.0),
 (4632, 0.04545454545454545),
 (4631, 0.0),
 (4630, 0.0),
 (4629, 0.07658395810674835),
 (4628, 0.0),
 (4627, 0.026444294267397254),
 (4626, 0.10660035817780521),
 (4625, 0.0),
 (4624, 0.0337099931231621),
 (4623, 0.08528028654224418),
 (4622, 0.0),
 (4621, 0.0),
 (4620, 0.03289758474798845),
 (4619, 0.0),
 (4618, 0.0),
 (4617, 0.0),
 (4616, 0.0),
 (4615, 0.0),
 (4614, 0.0),
 (4613, 0.027756369082668448),
 (4612, 0.0),
 (4611, 0.0),
 (4610, 0.03143473067309657),
 (4609, 0.0),
 (4608, 0.062197041357112286),
 (4607, 0.0),
 (4606, 0.0),
 (4605, 0.0),
 (4604, 0.044455422447438706),
 (4603, 0.027756369082668448),
 (4602, 0.07106690545187014),
 (4601, 0.0),
 (4600, 0.0),
 (4599, 0.0),
 (4598, 0.04181210050035454),
 (4597, 0.02823912473624525),
 (4596, 0.1348399724926484),
 (4595, 0.0),
 (4594, 0.0),
 (4593, 0.0),
 (4592, 0.02530226996846287),
 (4591, 0.0),
 (4590, 0.03143473067309657),
 (4589, 0.0),
 (4588, 0.0),
 (4587, 0.0),
 (4586, 0.025125945381480302),
 (4585, 0.0),
 (4584, 0.036037498507822355),
 (4583, 0.05698028822981897),
 (4582, 0.04624972900628802),
 (4581, 0.0),
 (4580, 0.04181210050035454),
 (4579, 0.0),
 (4578, 0.03829197905337418),
 (4577, 0.0),
 (4576, 0.0),
 (4575, 0.03553345272593507),
 (4574, 0.0),
 (4573, 0.0),
 (4572, 0.05504818825631802),
 (4571, 0.0),
 (4570, 0.039590379123244784),
 (4569, 0.03768891807222045),
 (4568, 0.10660035817780521),
 (4567, 0.0),
 (4566, 0.12087344460380703),
 (4565, 0.01930228591205457),
 (4564, 0.05504818825631802),
 (4563, 0.0),
 (4562, 0.09534625892455922),
 (4561, 0.04351941398892446),
 (4560, 0.07422696190252055),
 (4559, 0.0),
 (4558, 0.13318543164240537),
 (4557, 0.10050378152592121),
 (4556, 0.0),
 (4555, 0.0),
 (4554, 0.0),
 (4553, 0.0),
 (4552, 0.027076518053694116),
 (4551, 0.0674199862463242),
 (4550, 0.0),
 (4549, 0.03143473067309657),
 (4548, 0.0),
 (4547, 0.023688968483956713),
 (4546, 0.0),
 (4545, 0.050251890762960605),
 (4544, 0.0),
 (4543, 0.0),
 (4542, 0.14673479641335552),
 (4541, 0.0),
 (4540, 0.0),
 (4539, 0.0),
 (4538, 0.0298540717013266),
 (4537, 0.0),
 (4536, 0.0),
 (4535, 0.0),
 (4534, 0.0),
 (4533, 0.0),
 (4532, 0.02198997485667712),
 (4531, 0.0),
 (4530, 0.0),
 (4529, 0.016497966750889208),
 (4528, 0.0),
 (4527, 0.06356417261637282),
 (4526, 0.0),
 (4525, 0.0),
 (4524, 0.03143473067309657),
 (4523, 0.03143473067309657),
 (4522, 0.0),
 (4521, 0.04264014327112209),
 (4520, 0.028490144114909487),
 (4519, 0.09869275424396534),
 (4518, 0.0),
 (4517, 0.0),
 (4516, 0.05698028822981897),
 (4515, 0.0),
 (4514, 0.0),
 (4513, 0.022473328748774734),
 (4512, 0.0),
 (4511, 0.0),
 (4510, 0.0337099931231621),
 (4509, 0.0),
 (4508, 0.03143473067309657),
 (4507, 0.06154574548966637),
 (4506, 0.0),
 (4505, 0.0),
 (4504, 0.0),
 (4503, 0.04264014327112209),
 (4502, 0.12309149097933274),
 (4501, 0.0),
 (4500, 0.0),
 (4499, 0.03829197905337418),
 (4498, 0.03289758474798845),
 (4497, 0.0),
 (4496, 0.050251890762960605),
 (4495, 0.037113480951260276),
 (4494, 0.0),
 (4493, 0.0),
 (4492, 0.053300179088902604),
 (4491, 0.041030496993110906),
 (4490, 0.1305582419667734),
 (4489, 0.0),
 (4488, 0.0),
 (4487, 0.02874797872880345),
 (4486, 0.044455422447438706),
 (4485, 0.07784989441615228),
 (4484, 0.05504818825631802),
 (4483, 0.0),
 (4482, 0.0),
 (4481, 0.03768891807222045),
 (4480, 0.02799462554779271),
 (4479, 0.0),
 (4478, 0.019795189561622392),
 (4477, 0.0),
 (4476, 0.0),
 (4475, 0.03768891807222045),
 (4474, 0.04767312946227961),
 (4473, 0.050251890762960605),
 (4472, 0.08528028654224418),
 (4471, 0.02495325642529748),
 (4470, 0.0),
 (4469, 0.0674199862463242),
 (4468, 0.07312724241271305),
 (4467, 0.0),
 (4466, 0.025666350116967267),
 (4465, 0.0),
 (4464, 0.0),
 (4463, 0.09534625892455922),
 (4462, 0.0),
 (4461, 0.0),
 (4460, 0.0),
 (4459, 0.0),
 (4458, 0.032141217326661246),
 (4457, 0.0),
 (4456, 0.11677484162422842),
 (4455, 0.0),
 (4454, 0.04767312946227961),
 (4453, 0.08189266356489211),
 (4452, 0.0),
 (4451, 0.05913123959890826),
 (4450, 0.0),
 (4449, 0.02752409412815901),
 (4448, 0.019544077624852607),
 (4447, 0.0),
 (4446, 0.031098520678556143),
 (4445, 0.0),
 (4444, 0.0),
 (4443, 0.0),
 (4442, 0.0),
 (4441, 0.0),
 (4440, 0.0),
 (4439, 0.0),
 (4438, 0.03413943709994594),
 (4437, 0.0),
 (4436, 0.0),
 (4435, 0.0),
 (4434, 0.04264014327112209),
 (4433, 0.08362420100070908),
 (4432, 0.055512738165336896),
 (4431, 0.04767312946227961),
 (4430, 0.02530226996846287),
 (4429, 0.0971859061499725),
 (4428, 0.0),
 (4427, 0.05857074126574227),
 (4426, 0.0),
 (4425, 0.06356417261637282),
 (4424, 0.0),
 (4423, 0.0597081434026532),
 (4422, 0.0),
 (4421, 0.044455422447438706),
 (4420, 0.0),
 (4419, 0.0),
 (4418, 0.0),
 (4417, 0.0),
 (4416, 0.0),
 (4415, 0.05698028822981897),
 (4414, 0.0),
 (4413, 0.0),
 (4412, 0.04891159880445184),
 (4411, 0.0),
 (4410, 0.0),
 (4409, 0.0),
 (4408, 0.0),
 (4407, 0.10341753799900381),
 (4406, 0.037113480951260276),
 (4405, 0.24618298195866548),
 (4404, 0.0),
 (4403, 0.04264014327112209),
 (4402, 0.039590379123244784),
 (4401, 0.0),
 (4400, 0.0),
 (4399, 0.12060453783110543),
 (4398, 0.030151134457776358),
 (4397, 0.0),
 (4396, 0.0),
 (4395, 0.0),
 (4394, 0.050251890762960605),
 (4393, 0.0),
 (4392, 0.0895622151039798),
 (4391, 0.0),
 (4390, 0.050251890762960605),
 (4389, 0.03656362120635653),
 (4388, 0.023688968483956713),
 (4387, 0.022599230735278433),
 (4386, 0.0),
 (4385, 0.0),
 (4384, 0.02874797872880345),
 (4383, 0.09196009797434056),
 (4382, 0.0),
 (4381, 0.0),
 (4380, 0.0),
 (4379, 0.0),
 (4378, 0.0),
 (4377, 0.0),
 (4376, 0.0),
 (4375, 0.0),
 (4374, 0.03413943709994594),
 (4373, 0.0),
 (4372, 0.030772872744833184),
 (4371, 0.0),
 (4370, 0.0),
 (4369, 0.0),
 (4368, 0.0),
 (4367, 0.0),
 (4366, 0.0650256088762355),
 (4365, 0.0),
 (4364, 0.02686076546751267),
 (4363, 0.0),
 (4362, 0.0),
 (4361, 0.0),
 (4360, 0.0),
 (4359, 0.0),
 (4358, 0.0),
 (4357, 0.12309149097933272),
 (4356, 0.03289758474798845),
 (4355, 0.08362420100070908),
 (4354, 0.0),
 (4353, 0.05913123959890826),
 (4352, 0.0),
 (4351, 0.0),
 (4350, 0.0),
 (4349, 0.0),
 (4348, 0.17739371879672478),
 (4347, 0.0),
 (4346, 0.0),
 (4345, 0.0),
 (4344, 0.07009996372327816),
 (4343, 0.14782809899727065),
 (4342, 0.05698028822981897),
 (4341, 0.06827887419989188),
 (4340, 0.02874797872880345),
 (4339, 0.03553345272593507),
 (4338, 0.0),
 (4337, 0.0),
 (4336, 0.16448792373994225),
 (4335, 0.0),
 (4334, 0.0),
 (4333, 0.0),
 (4332, 0.04767312946227961),
 (4331, 0.08206099398622181),
 (4330, 0.10050378152592121),
 (4329, 0.09988907373180403),
 (4328, 0.0),
 (4327, 0.0),
 (4326, 0.0),
 (4325, 0.0),
 (4324, 0.0),
 (4323, 0.0),
 (4322, 0.0),
 (4321, 0.0),
 (4320, 0.08058229640253801),
 (4319, 0.062418778393235924),
 (4318, 0.0),
 (4317, 0.0),
 (4316, 0.06917144638660747),
 (4315, 0.0),
 (4314, 0.025125945381480302),
 (4313, 0.07422696190252055),
 (4312, 0.0),
 (4311, 0.0),
 (4310, 0.0),
 (4309, 0.0),
 (4308, 0.04545454545454545),
 (4307, 0.0),
 (4306, 0.0),
 (4305, 0.0),
 (4304, 0.029012942659282972),
 (4303, 0.04545454545454545),
 (4302, 0.0),
 (4301, 0.07784989441615228),
 (4300, 0.0),
 (4299, 0.0),
 (4298, 0.0),
 (4297, 0.04181210050035454),
 (4296, 0.03768891807222045),
 (4295, 0.03504998186163908),
 (4294, 0.0),
 (4293, 0.0),
 (4292, 0.0),
 (4291, 0.0),
 (4290, 0.0909090909090909),
 (4289, 0.0),
 (4288, 0.06827887419989188),
 (4287, 0.0),
 (4286, 0.030772872744833184),
 (4285, 0.044455422447438706),
 (4284, 0.0),
 (4283, 0.0),
 (4282, 0.0),
 (4281, 0.0674199862463242),
 (4280, 0.031098520678556143),
 (4279, 0.05170876899950191),
 (4278, 0.0),
 (4277, 0.07435223956449145),
 (4276, 0.0),
 (4275, 0.0),
 (4274, 0.0),
 (4273, 0.0),
 (4272, 0.0),
 (4271, 0.08362420100070908),
 (4270, 0.07784989441615228),
 (4269, 0.0),
 (4268, 0.0),
 (4267, 0.0),
 (4266, 0.0),
 (4265, 0.08189266356489211),
 (4264, 0.0),
 (4263, 0.0),
 (4262, 0.0),
 (4261, 0.03178208630818641),
 (4260, 0.03892494720807614),
 (4259, 0.05170876899950191),
 (4258, 0.0),
 (4257, 0.03768891807222045),
 (4256, 0.04767312946227961),
 (4255, 0.09304842103984708),
 (4254, 0.04264014327112209),
 (4253, 0.030151134457776358),
 (4252, 0.0909090909090909),
 (4251, 0.0),
 (4250, 0.03413943709994594),
 (4249, 0.0),
 (4248, 0.06428243465332249),
 (4247, 0.0),
 (4246, 0.0),
 (4245, 0.02530226996846287),
 (4244, 0.0),
 (4243, 0.0),
 (4242, 0.01922366120271981),
 (4241, 0.0),
 (4240, 0.10050378152592121),
 (4239, 0.0),
 (4238, 0.0),
 (4237, 0.09782319760890368),
 (4236, 0.0657951694959769),
 (4235, 0.02823912473624525),
 (4234, 0.0),
 (4233, 0.021427478217774167),
 (4232, 0.0),
 (4231, 0.0),
 (4230, 0.0),
 (4229, 0.0),
 (4228, 0.1011299793694863),
 (4227, 0.04264014327112209),
 (4226, 0.0),
 (4225, 0.05857074126574227),
 (4224, 0.025482359571881275),
 (4223, 0.036166897482533655),
 (4222, 0.03768891807222045),
 (4221, 0.0),
 (4220, 0.04828045495852675),
 (4219, 0.0),
 (4218, 0.04029114820126901),
 (4217, 0.0),
 (4216, 0.0),
 (4215, 0.0597081434026532),
 (4214, 0.0),
 (4213, 0.03251280443811775),
 (4212, 0.060914490387317256),
 (4211, 0.03553345272593507),
 (4210, 0.05698028822981897),
 (4209, 0.0),
 (4208, 0.0),
 (4207, 0.0),
 (4206, 0.11877113736973435),
 (4205, 0.0),
 (4204, 0.0),
 (4203, 0.0),
 (4202, 0.0),
 (4201, 0.0),
 (4200, 0.04351941398892446),
 (4199, 0.0),
 (4198, 0.0),
 (4197, 0.032141217326661246),
 (4196, 0.08703882797784893),
 (4195, 0.0),
 (4194, 0.08058229640253801),
 (4193, 0.0),
 (4192, 0.02956561979945413),
 (4191, 0.0),
 (4190, 0.08891084489487741),
 (4189, 0.0),
 (4188, 0.0),
 (4187, 0.0),
 (4186, 0.0),
 (4185, 0.032141217326661246),
 (4184, 0.0),
 (4183, 0.0),
 (4182, 0.0),
 (4181, 0.0),
 (4180, 0.0),
 (4179, 0.05415303610738823),
 (4178, 0.030457245193658628),
 (4177, 0.0298540717013266),
 (4176, 0.02686076546751267),
 (4175, 0.04351941398892446),
 (4174, 0.0),
 (4173, 0.0337099931231621),
 (4172, 0.0),
 (4171, 0.0),
 (4170, 0.032141217326661246),
 (4169, 0.0),
 (4168, 0.0),
 (4167, 0.08122955416108235),
 (4166, 0.0),
 (4165, 0.03413943709994594),
 (4164, 0.039590379123244784),
 (4163, 0.10050378152592121),
 (4162, 0.0),
 (4161, 0.0),
 (4160, 0.023836564731139806),
 (4159, 0.022227711223719353),
 (4158, 0.058025885318565944),
 (4157, 0.0),
 (4156, 0.0),
 (4155, 0.0),
 (4154, 0.03458572319330373),
 (4153, 0.032141217326661246),
 (4152, 0.07872958216222169),
 (4151, 0.0),
 (4150, 0.07784989441615228),
 (4149, 0.03683547343418786),
 (4148, 0.04029114820126901),
 (4147, 0.050251890762960605),
 (4146, 0.12856486930664499),
 (4145, 0.05913123959890826),
 (4144, 0.04545454545454545),
 (4143, 0.0),
 (4142, 0.0),
 (4141, 0.03656362120635653),
 (4140, 0.03458572319330373),
 (4139, 0.03768891807222045),
 (4138, 0.0),
 (4137, 0.053300179088902604),
 (4136, 0.0),
 (4135, 0.08891084489487741),
 (4134, 0.0),
 (4133, 0.13957263155977062),
 (4132, 0.03458572319330373),
 (4131, 0.0564782494724905),
 (4130, 0.04545454545454545),
 (4129, 0.04891159880445184),
 (4128, 0.050251890762960605),
 (4127, 0.09772038812426304),
 (4126, 0.04652421051992354),
 (4125, 0.0),
 (4124, 0.0),
 (4123, 0.03656362120635653),
 (4122, 0.0),
 (4121, 0.0895622151039798),
 (4120, 0.04891159880445184),
 (4119, 0.0),
 (4118, 0.05248638810814779),
 (4117, 0.039590379123244784),
 (4116, 0.0),
 (4115, 0.0597081434026532),
 (4114, 0.0),
 (4113, 0.0),
 (4112, 0.03892494720807614),
 (4111, 0.0),
 (4110, 0.0),
 (4109, 0.0),
 (4108, 0.0),
 (4107, 0.03553345272593507),
 (4106, 0.0),
 (4105, 0.0),
 (4104, 0.0),
 (4103, 0.02686076546751267),
 (4102, 0.0),
 (4101, 0.024618298195866542),
 (4100, 0.0),
 (4099, 0.0),
 (4098, 0.0),
 (4097, 0.07784989441615228),
 (4096, 0.0),
 (4095, 0.0),
 (4094, 0.03143473067309657),
 (4093, 0.0),
 (4092, 0.0),
 (4091, 0.0),
 (4090, 0.0),
 (4089, 0.039590379123244784),
 (4088, 0.03504998186163908),
 (4087, 0.0),
 (4086, 0.05209322610706232),
 (4085, 0.03251280443811775),
 (4084, 0.03504998186163908),
 (4083, 0.0),
 (4082, 0.0298540717013266),
 (4081, 0.1257389226923863),
 (4080, 0.0),
 (4079, 0.0),
 (4078, 0.03143473067309657),
 (4077, 0.03458572319330373),
 (4076, 0.06917144638660747),
 (4075, 0.10497277621629558),
 (4074, 0.05170876899950191),
 (4073, 0.05504818825631802),
 (4072, 0.0),
 (4071, 0.02285751604412472),
 (4070, 0.04351941398892446),
 (4069, 0.0),
 (4068, 0.0),
 (4067, 0.0),
 (4066, 0.0),
 (4065, 0.060302268915552716),
 (4064, 0.04891159880445184),
 (4063, 0.0),
 (4062, 0.0),
 (4061, 0.0),
 (4060, 0.0),
 (4059, 0.04351941398892446),
 (4058, 0.0),
 (4057, 0.0),
 (4056, 0.0),
 (4055, 0.0),
 (4054, 0.0),
 (4053, 0.07106690545187014),
 (4052, 0.0),
 (4051, 0.0),
 (4050, 0.0),
 (4049, 0.0),
 (4048, 0.0),
 (4047, 0.0),
 (4046, 0.12476628212648741),
 (4045, 0.03289758474798845),
 (4044, 0.0),
 (4043, 0.09988907373180403),
 (4042, 0.0),
 (4041, 0.0),
 (4040, 0.0),
 (4039, 0.0),
 (4038, 0.05170876899950191),
 (4037, 0.03768891807222045),
 (4036, 0.04181210050035454),
 (4035, 0.037113480951260276),
 (4034, 0.0),
 (4033, 0.0),
 (4032, 0.0),
 (4031, 0.0),
 (4030, 0.037113480951260276),
 (4029, 0.0),
 (4028, 0.0),
 (4027, 0.0),
 (4026, 0.018281810603178263),
 (4025, 0.0),
 (4024, 0.0),
 (4023, 0.0),
 (4022, 0.021873931962990353),
 (4021, 0.0),
 (4020, 0.02604661305353116),
 (4019, 0.0),
 (4018, 0.04545454545454545),
 (4017, 0.04351941398892446),
 (4016, 0.1305582419667734),
 (4015, 0.05288858853479451),
 (4014, 0.0),
 (4013, 0.02023611646290882),
 (4012, 0.0),
 (4011, 0.0),
 (4010, 0.0),
 (4009, 0.0),
 (4008, 0.20683507599800763),
 (4007, 0.036037498507822355),
 (4006, 0.0),
 (4005, 0.0),
 (4004, 0.0),
 (4003, 0.0),
 (4002, 0.028490144114909487),
 (4001, 0.025666350116967267),
 (4000, 0.04598004898717028),
 (3999, 0.0),
 (3998, 0.05170876899950191),
 (3997, 0.19795189561622392),
 (3996, 0.0),
 (3995, 0.08326910724800535),
 (3994, 0.0),
 (3993, 0.0),
 (3992, 0.08703882797784893),
 (3991, 0.023836564731139806),
 (3990, 0.030151134457776358),
 (3989, 0.0),
 (3988, 0.0),
 (3987, 0.0),
 (3986, 0.05504818825631802),
 (3985, 0.0),
 (3984, 0.02956561979945413),
 (3983, 0.05170876899950191),
 (3982, 0.03768891807222045),
 (3981, 0.041030496993110906),
 (3980, 0.044455422447438706),
 (3979, 0.05814564991516647),
 (3978, 0.0),
 (3977, 0.0),
 (3976, 0.05504818825631802),
 (3975, 0.0),
 (3974, 0.0),
 (3973, 0.04652421051992354),
 (3972, 0.0),
 (3971, 0.08891084489487741),
 (3970, 0.09534625892455922),
 (3969, 0.04652421051992354),
 (3968, 0.0),
 (3967, 0.0),
 (3966, 0.041030496993110906),
 (3965, 0.04652421051992354),
 (3964, 0.0),
 (3963, 0.0),
 (3962, 0.0),
 (3961, 0.05096471914376255),
 (3960, 0.050251890762960605),
 (3959, 0.02299002449358514),
 (3958, 0.02061089119916432),
 (3957, 0.0),
 (3956, 0.08398387664337813),
 (3955, 0.0),
 (3954, 0.03829197905337418),
 (3953, 0.0),
 (3952, 0.044455422447438706),
 (3951, 0.0),
 (3950, 0.07207499701564471),
 (3949, 0.019881069312188603),
 (3948, 0.0),
 (3947, 0.05698028822981897),
 (3946, 0.04990651285059496),
 (3945, 0.02354408046740055),
 (3944, 0.08362420100070908),
 (3943, 0.0),
 (3942, 0.062197041357112286),
 (3941, 0.0),
 (3940, 0.0),
 (3939, 0.05504818825631802),
 (3938, 0.029285370632871136),
 (3937, 0.0),
 (3936, 0.0),
 (3935, 0.0),
 (3934, 0.0),
 (3933, 0.03251280443811775),
 (3932, 0.0),
 (3931, 0.041030496993110906),
 (3930, 0.0),
 (3929, 0.0),
 (3928, 0.0),
 (3927, 0.0),
 (3926, 0.0),
 (3925, 0.0),
 (3924, 0.07106690545187014),
 (3923, 0.0),
 (3922, 0.0),
 (3921, 0.0),
 (3920, 0.0),
 (3919, 0.0),
 (3918, 0.0),
 (3917, 0.0),
 (3916, 0.050251890762960605),
 (3915, 0.0),
 (3914, 0.03553345272593507),
 (3913, 0.03458572319330373),
 (3912, 0.05504818825631802),
 (3911, 0.02340181886004545),
 (3910, 0.03289758474798845),
 (3909, 0.04181210050035454),
 (3908, 0.05913123959890826),
 (3907, 0.0),
 (3906, 0.05209322610706232),
 (3905, 0.09137173558097589),
 (3904, 0.018018749253911177),
 (3903, 0.08189266356489211),
 (3902, 0.0),
 (3901, 0.03504998186163908),
 (3900, 0.0657951694959769),
 (3899, 0.04264014327112209),
 (3898, 0.0),
 (3897, 0.029012942659282972),
 (3896, 0.0),
 (3895, 0.019881069312188603),
 (3894, 0.0),
 (3893, 0.0),
 (3892, 0.06917144638660747),
 (3891, 0.0),
 (3890, 0.0),
 (3889, 0.0909090909090909),
 (3888, 0.07658395810674835),
 (3887, 0.0),
 (3886, 0.06154574548966637),
 (3885, 0.0),
 (3884, 0.0),
 (3883, 0.0),
 (3882, 0.0),
 (3881, 0.08528028654224418),
 (3880, 0.0),
 (3879, 0.0),
 (3878, 0.025666350116967267),

In [ ]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

In [ ]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [ ]:
recommend('Falcon Rising')

10th & Wolf
Street Kings
Ladder 49
Sexy Beast
Get Carter

In [ ]:
pwd

'/content/drive/MyDrive/Colab Notebooks'

In [ ]:
import pickle as pkl

In [ ]:
new_df.head()

,title,id,tags
0,Avatar,19995,"in the 22nd century, a parapleg marin is dispa..."
1,Pirates of the Caribbean: At World's End,285,"captain barbossa, long believ to be dead, ha c..."
2,Spectre,206647,a cryptic messag from bond’ past send him on a...
3,The Dark Knight Rises,49026,follow the death of district attorney harvey d...
4,John Carter,49529,"john carter is a war-weary, former militari ca..."

from matplotlib import pyplot as plt
_df_0['id'].plot(kind='hist', bins=20, title='id')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('title').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('tags').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['id'].plot(kind='line', figsize=(8, 4), title='id')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['tags'].value_counts()
    for x_label, grp in _df_4.groupby('title')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('title')
_ = plt.ylabel('tags')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_5['title'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_5, x='id', y='title', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_6['tags'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_6, x='id', y='tags', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)